//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.1022
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MijoCommander.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MijoCommander.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_border_0 {
            get {
                object obj = ResourceManager.GetObject("fatcow_border_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_border_1 {
            get {
                object obj = ResourceManager.GetObject("fatcow_border_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_border_2 {
            get {
                object obj = ResourceManager.GetObject("fatcow_border_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_border_inside {
            get {
                object obj = ResourceManager.GetObject("fatcow_border_inside", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_border_top {
            get {
                object obj = ResourceManager.GetObject("fatcow_border_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_cancel {
            get {
                object obj = ResourceManager.GetObject("fatcow_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_color_swatch {
            get {
                object obj = ResourceManager.GetObject("fatcow_color_swatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_disk {
            get {
                object obj = ResourceManager.GetObject("fatcow_disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_door {
            get {
                object obj = ResourceManager.GetObject("fatcow_door", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_gear {
            get {
                object obj = ResourceManager.GetObject("fatcow_gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_help {
            get {
                object obj = ResourceManager.GetObject("fatcow_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_information {
            get {
                object obj = ResourceManager.GetObject("fatcow_information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_palette {
            get {
                object obj = ResourceManager.GetObject("fatcow_palette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_split_panel {
            get {
                object obj = ResourceManager.GetObject("fatcow_split_panel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_split_panel_vertical {
            get {
                object obj = ResourceManager.GetObject("fatcow_split_panel_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_table {
            get {
                object obj = ResourceManager.GetObject("fatcow_table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_table_select_cell {
            get {
                object obj = ResourceManager.GetObject("fatcow_table_select_cell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_table_select_row {
            get {
                object obj = ResourceManager.GetObject("fatcow_table_select_row", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_tick {
            get {
                object obj = ResourceManager.GetObject("fatcow_tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_tick_button {
            get {
                object obj = ResourceManager.GetObject("fatcow_tick_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_toolbar {
            get {
                object obj = ResourceManager.GetObject("fatcow_toolbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_toolbar_add {
            get {
                object obj = ResourceManager.GetObject("fatcow_toolbar_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_toolbar_delete {
            get {
                object obj = ResourceManager.GetObject("fatcow_toolbar_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_view_left_minus {
            get {
                object obj = ResourceManager.GetObject("fatcow_view_left_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_view_left_plus {
            get {
                object obj = ResourceManager.GetObject("fatcow_view_left_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_view_no_collapse {
            get {
                object obj = ResourceManager.GetObject("fatcow_view_no_collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_view_right_minus {
            get {
                object obj = ResourceManager.GetObject("fatcow_view_right_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_view_right_plus {
            get {
                object obj = ResourceManager.GetObject("fatcow_view_right_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fatcow_wrench {
            get {
                object obj = ResourceManager.GetObject("fatcow_wrench", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_border_0 {
            get {
                object obj = ResourceManager.GetObject("fugue_border_0", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_border_1 {
            get {
                object obj = ResourceManager.GetObject("fugue_border_1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_border_2 {
            get {
                object obj = ResourceManager.GetObject("fugue_border_2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_border_inside {
            get {
                object obj = ResourceManager.GetObject("fugue_border_inside", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_border_top {
            get {
                object obj = ResourceManager.GetObject("fugue_border_top", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_cancel {
            get {
                object obj = ResourceManager.GetObject("fugue_cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_color_swatch {
            get {
                object obj = ResourceManager.GetObject("fugue_color_swatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_disk {
            get {
                object obj = ResourceManager.GetObject("fugue_disk", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_door {
            get {
                object obj = ResourceManager.GetObject("fugue_door", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_gear {
            get {
                object obj = ResourceManager.GetObject("fugue_gear", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_help {
            get {
                object obj = ResourceManager.GetObject("fugue_help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_information {
            get {
                object obj = ResourceManager.GetObject("fugue_information", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_palette {
            get {
                object obj = ResourceManager.GetObject("fugue_palette", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_split_panel {
            get {
                object obj = ResourceManager.GetObject("fugue_split_panel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_split_panel_vertical {
            get {
                object obj = ResourceManager.GetObject("fugue_split_panel_vertical", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_table {
            get {
                object obj = ResourceManager.GetObject("fugue_table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_table_select_cell {
            get {
                object obj = ResourceManager.GetObject("fugue_table_select_cell", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_table_select_row {
            get {
                object obj = ResourceManager.GetObject("fugue_table_select_row", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_tick {
            get {
                object obj = ResourceManager.GetObject("fugue_tick", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_tick_button {
            get {
                object obj = ResourceManager.GetObject("fugue_tick_button", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_toolbar {
            get {
                object obj = ResourceManager.GetObject("fugue_toolbar", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_toolbar_add {
            get {
                object obj = ResourceManager.GetObject("fugue_toolbar_add", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_toolbar_delete {
            get {
                object obj = ResourceManager.GetObject("fugue_toolbar_delete", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_view_left_minus {
            get {
                object obj = ResourceManager.GetObject("fugue_view_left_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_view_left_plus {
            get {
                object obj = ResourceManager.GetObject("fugue_view_left_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_view_no_collapse {
            get {
                object obj = ResourceManager.GetObject("fugue_view_no_collapse", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_view_right_minus {
            get {
                object obj = ResourceManager.GetObject("fugue_view_right_minus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_view_right_plus {
            get {
                object obj = ResourceManager.GetObject("fugue_view_right_plus", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap fugue_wrench {
            get {
                object obj = ResourceManager.GetObject("fugue_wrench", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Error ähnelt.
        /// </summary>
        internal static string msgError {
            get {
                return ResourceManager.GetString("msgError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Folder doesn&apos;t exist. ähnelt.
        /// </summary>
        internal static string msgFolderNotExist {
            get {
                return ResourceManager.GetString("msgFolderNotExist", resourceCulture);
            }
        }
    }
}
